# CodeRabbit Configuration Template
# Complete reference: https://docs.coderabbit.ai/reference/configuration
# Copy this file to .coderabbit.yaml in your repository root

# =============================================================================
# GLOBAL SETTINGS
# These settings apply to your entire CodeRabbit configuration
# =============================================================================

# Set the language for reviews by using the corresponding ISO language code.
# Options: de, de-DE, de-AT, de-CH, en, en-US, en-AU, en-GB, en-CA, en-NZ, en-ZA, es, es-AR, fr, fr-CA, fr-CH, fr-BE, nl, nl-BE, pt-AO, pt, pt-BR, pt-MZ, pt-PT, ar, ast-ES, ast, be-BY, be, br-FR, br, ca-ES, ca, ca-ES-valencia, ca-ES-balear, da-DK, da, de-DE-x-simple-language, el-GR, el, eo, fa, ga-IE, ga, gl-ES, gl, it, ja-JP, ja, km-KH, km, ko-KR, ko, pl-PL, pl, ro-RO, ro, ru-RU, ru, sk-SK, sk, sl-SI, sl, sv, ta-IN, ta, tl-PH, tl, tr, uk-UA, uk, zh-CN, zh, crh-UA, crh, cs-CZ, cs, nb, no, nl-NL, de-DE-x-simple-language-DE, es-ES, it-IT, fa-IR, sv-SE, de-LU, fr-FR, bg-BG, bg, he-IL, he, hi-IN, hi, vi-VN, vi, th-TH, th, bn-BD, bn
# Default: "en-US"
language: "en-US"

# =============================================================================
# REVIEWS
# Settings related to reviews.
# =============================================================================

# Settings related to reviews.
# Default: {}
reviews:

  # Set the profile for reviews. Assertive profile yields more feedback, that may be considered nitpicky.
  # Options: chill, assertive
  # Default: "chill"
  profile: "chill"

  # Approve the review once CodeRabbit’s comments are resolved and no pre-merge checks are in an error state. Note: In GitLab, all discussions must be resolved.
  # Default: false
  request_changes_workflow: true

  # Configuration for auto review
  # Default: {}
  auto_review:

    # Automatic Review - Automatic code review
    # Default: true
    enabled: true

    # Review draft PRs/MRs.
    # Default: false
    drafts: false

  # Path-specific review instructions
  path_instructions:
    - path: "app/**/*.tsx"
      instructions: |
        You are an expert Next.Js developer. Provide suggestions to improve the code in the following areas:
        - optimize component structure and hooks
        - address accessibility and theme support
        - secure event handlers and prop validation

    - path: "app/lib/actions/*.ts"
      instructions: |
        You are an expert Next.Js developer. Provide suggestions to improve the code in the following areas:
        - validate inputs and handle errors
        - check auth, rate limiting and DB code_optimization

    - path: "lib/supabase/*.ts"
      instructions: |
        You are an expert Next.Js developer. Provide suggestions to improve the code in the following areas:
        - review DB queries, auth and data encryption
        - monitor for sensitive data leaks
